environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

before_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "cd dist"
  - "%PYTHON%\\python.exe -m pip install --find-links=. atari-py"
  - "%PYTHON%\\python.exe -m pip install gym"

test_script:
  - "%PYTHON%\\python.exe -c \"import gym; env = gym.make('Enduro-v0'); env.reset(); [env.step(env.action_space.sample()) for i in range(1000)]\""

artifacts:
  - path: dist\*.whl
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "Weh3LepGE4k174U43zSHYAiM1pUCUSlQ+wjwpmUI2X3SsZqTpdRKzDUwkLnHjp23"
  artifact: /.*\.whl/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
